# build.yml
name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure dependencies
      uses: ilammy/msvc-dev-cmd@v1

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - run: REG IMPORT .github/workflows/DefaultProjectExtension.reg

    - working-directory: ./src
      shell: cmd
      run: createallprojects.bat

    - working-directory: ./src
      shell: bash
      run: ./devtools/fixsln.sh everything.sln

    - name: Build
      run: cd src; devenv everything.sln /Build Release